server:
  port: 8080
  servlet:
    context-path: /account
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.3306/account?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
